config/routes.rb
Rails.application.routes.draw do
  
  get 'places/check'
  get 'places/category'
   resources :places do 
   	resources :comments
   	resources :categories
   end

  root 'places#index'
  root 'places#new'
  root 'places#check'
  root 'places#submit'
 
  root to: 'session#index'
  root to: 'login#index'

resources :places do
    collection do
   get 'category', to: "places#category"


    end
  end

resources :login do
    collection do
      get 'signup', to: "login#new"
      get 'login', to: "login#index"
      post 'login', to: "login#login"
      get 'dashboard', to: "login#dashboard"
      get 'approve',to: "login#approve"
      get 'decline',to: "login#decline"
      get 'deniedboard',to: "login#denied"
      get 'acceptboard',to: "login#accept"
      post 'create',to: "login#show"


    end
  end

   resources :session do
    collection do
      get 'signup', to: "session#new"
      get 'login', to: "session#index"
      post 'login', to: "session#login"
      get 'logout', to: "session#logout"
      get 'dashboard', to: "session#dashboard"
    end
  end

 end

app/controllers/session_controller.rb
class SessionController < ApplicationController
   layout "session"
    skip_before_action :require_user, only: [:index, :login, :new, :create]

    def index 
        @user=User.new
         @categories = Category.all
    end

   def login
        islogged=false
        if !params[:user][:email].blank? and !params[:user][:password].blank? 
            user = User.find_by(email: params[:user][:email])    
            if user and user.authenticate(params[:user][:password])
                session[:user_id]=user.id
                session[:user_name] = user.name
                islogged=true
            end    
        end    
        if islogged
            redirect_to places_path
        else 
            flash[:danger] = 'Invalid email/password combination' 
            @user=User.new
            render 'index'    
        end
    end    

    def dashboard
   @categories = Category.all
        
    @user = User.find(session[:user_id])
    @dashboard = @user.places
    end

    def new
        @categories = Category.all
        @user=User.new
    end

    def create
        @categories = Category.all
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            session[:user_name] = @user.name
            redirect_to places_path
        else
            render 'new'
        end
    end

    def edit
        @categories = Category.all
        @user = User.find(session[:user_id])
    end

    def update
        @categories = Category.all
        @user = User.find(session[:user_id])
        @user.update(user_params)
        redirect_to places_index_path
        
    end

    def logout
        session[:user_id] = nil
        session[:user_name] = nil
        flash[:success] = "Хэрэглэгч гарлаа"
        redirect_to login_session_index_path
    end 

    
    private
    def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/dashboard.html.erb
<%= stylesheet_link_tag 'index'%>
<div class="square">
  <div class = "container-fluid">
    <div class="row">
      <div class="col-sm-3">
      </div>
      <div class="col-sm-9">
        <h5>Нэмсэн газрууд</h5>
        <div class = "card-box container"> 
          <div class="card-deck ">
            <% @dashboard.each.with_index do |place,index| %>
            <div class="card" style="width: 18rem; max-width: 250px; min-width: 200px; margin-bottom: 20px; border-radius: 20px;">
              <div class = "photo">
                <%= image_tag place.image.to_s %>
                <div class="glow-wrap link ">
                  <i class="glow"></i>
                </div>
              </div>
              <div class="card-body">
                <div class="titles">
                  <%= link_to place.title, place_path(place) %><br>   
                </div>
                <div class="col-lg-12">
                  <div class="star">
                    <div class="<%=index%>">
                      <span class="fa fa-star-o" data-rating="1"></span>
                      <span class="fa fa-star-o" data-rating="2"></span>
                      <span class="fa fa-star-o" data-rating="3"></span>
                      <span class="fa fa-star-o" data-rating="4"></span>
                      <span class="fa fa-star-o" data-rating="5"></span>
                      <input type="hidden" name="whatever1" class="rating-value" value="<%=place.comments.average(:rating)%>">
                    </div>        
                  </div>
                </div>
                <div class = "description">
                  <%= place.description%>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">
                    <a href="places/1"><span class="fa fa-facebook iconlogo"></span> </a>
                    <a href=""><span class="fa fa-google logo iconlogo"></span></a>
                    <a href=""> <span class="fa fa-twitter iconlogo"></span></a>      
                  </li>  
                </ul>
              </div>
            </div> 
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <p id="demo"></p>
</div>
</div> 
<script>
  for (var i = 0; i < 4; i++) {
   var d = "'."+i+" .fa'";
   var $val = "'."+i+" .fa'";
   console.log($val);
   var $star_rating = $('.'+i+' .fa'); 
   console.log($star_rating);
   var SetRatingStar = function() {
    return $star_rating.each(function() {
      if (parseInt($star_rating.siblings('input.rating-value').val()) >= parseInt($(this).data('rating'))) {
        return $(this).removeClass('fa-star-o').addClass('fa-star');
      } else {
        return $(this).removeClass('fa-star').addClass('fa-star-o');
      }
    });
  };
  SetRatingStar();
  $(document).ready(function() {
  });
}
</script>

app/views/session/edit.html.erb
<%= stylesheet_link_tag    'edit' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<div id="login-box">
<div class="left-box">
    <h1>Хувийн мэдээлэл шинэчлэх</h1>
    <%= form_for(@user, url: session_path(id: params[:user_id]), method: "put") do |f| %>
        <% @user.errors.full_messages.each do |msg| %>
            <li class="error"><%= msg %></li>
          <% end %>

      <!-- Edit field -->

        <%= f.text_field :name, class: 'form-control', placeholder: "Хэрэглэгчийн нэр" %>
    
        <%= f.email_field :email, class: 'form-control', placeholder: "И-мэйл хаяг" %>
    
        <%= f.password_field :password, class: 'form-control', placeholder: "Нууц үг" %>

        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Нууц үг дахин оруулах" %>
    
        <%= f.submit "Хадгалах", class: "btn btn-primary" %>
    <% end %>
</div>

<!-- Social media sign-in -->
<div class="right-box">
    <span class="signinwith">Сошиалаар<br/>Нэвтрэх</span>

<button class="social facebook">Facebook нэвтрэх</button>    
<button class="social twitter">Twitter нэвтрэх</button> 
<button class="social google">Google+ нэвтрэх</button> 
</div>
</div>

app/views/session/index.html.erb
<div id="login-box">
    <div class="left-box">
        <h1>Нэвтрэх</h1>
        <%= form_for(@user, url: login_session_index_path) do |f| %>
            <% flash.each do |key, value| %>
                <div>
                      <%= value %>
                </div>
          <% end %>
            <%= f.email_field :email, class: 'form-control', placeholder: "И-мэйл хаяг" %>
        
            <%= f.password_field :password, class: 'form-control', placeholder: "Нууц үг" %>
        
            <%= f.submit "Нэвтрэх", class: "btn btn-primary" %>
        <% end %>

         <%= link_to 'Бүртгүүлэх', class: "btn btn-primary" ,controller: 'session', action: 'new' %>
         <%= link_to 'Админ', class: "btn btn-primary" ,controller: 'login', action: 'index' %>
    </div>
   
    <!-- Social media sign-in -->
    <div class="right-box">
        <span class="signinwith">Сошиалаар<br/>Нэвтрэх</span>

    <button class="social facebook">Facebook нэвтрэх</button>    
    <button class="social twitter">Twitter нэвтрэх</button> 
    <button class="social google">Google+ нэвтрэх</button> 
    </div>
</div>

app/views/session/new.html.erb
<div id="login-box">
<div class="left-box">
    <h1>Бүртгүүлэх</h1>
    <%= form_for(@user, url: session_index_path) do |f| %>
        <% @user.errors.full_messages.each do |msg| %>
            <li class="error"><%= msg %></li>
          <% end %>

      <!-- SignUp field -->
        <%= f.text_field :name, class: 'form-control', placeholder: "Хэрэглэгчийн нэр" %>

        <%= f.email_field :email, class: 'form-control', placeholder: "И-мэйл хаяг" %>
    
        <%= f.password_field :password, class: 'form-control', placeholder: "Нууц үг" %>

        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Нууц үг дахин оруулах" %>
    
        <%= f.submit "Бүртгүүлэх", class: "btn btn-primary" %>
    <% end %>
</div>

<!-- Social media sign-in -->
<div class="right-box">
    <span class="signinwith">Сошиалаар<br/>Нэвтрэх</span>

<button class="social facebook">Facebook нэвтрэх</button>    
<button class="social twitter">Twitter нэвтрэх</button> 
<button class="social google">Google+ нэвтрэх</button> 
</div>
</div>