config/routes.rb
Rails.application.routes.draw do
  
  get 'places/check'
  get 'places/category'
   resources :places do 
   	resources :comments
   	resources :categories
   end

  root 'places#index'
  root 'places#new'
  root 'places#check'
  root 'places#submit'
 
  root to: 'session#index'
  root to: 'login#index'

resources :places do
    collection do
   get 'category', to: "places#category"


    end
  end

resources :login do
    collection do
      get 'signup', to: "login#new"
      get 'login', to: "login#index"
      post 'login', to: "login#login"
      get 'dashboard', to: "login#dashboard"
      get 'approve',to: "login#approve"
      get 'decline',to: "login#decline"
      get 'deniedboard',to: "login#denied"
      get 'acceptboard',to: "login#accept"
      post 'create',to: "login#show"


    end
  end

   resources :session do
    collection do
      get 'signup', to: "session#new"
      get 'login', to: "session#index"
      post 'login', to: "session#login"
      get 'logout', to: "session#logout"
      get 'dashboard', to: "session#dashboard"
    end
  end

 end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	 def index 
       @admin=Admin.new
       @categories = Category.all
    end

    def login
        islogged=false
        if !params[:admin][:email].blank? and !params[:admin][:password].blank? 
            admin = Admin.find_by(email: params[:admin][:email])    
            if admin and admin.authenticate(params[:admin][:password])
                session[:admin_id]=admin.id
                islogged=true
            end    
        end    
        if islogged
            redirect_to dashboard_login_index_path
        else 
            flash[:danger] = 'Invalid email/password combination' 
            @admin=Admin.new
            render 'index'    
        end
    end    

    def dashboard
        @pending = Place.where(status: 0).paginate(:page => params[:page], per_page:8)
        @categories = Category.all
    
    end
    def denied
        @denied = Place.where(status: 2).paginate(:page => params[:page], per_page:8)
        @categories = Category.all
    end

    def accept
        @accept = Place.where(status: 1).paginate(:page => params[:page], per_page:8)
        @categories = Category.all
    end
    
    def approve
          @categories = Category.all
          @place = Place.find(params[:place]) 
          puts "-------------------------------"
          puts params[:place]
          puts "-------------------------------"
          @place.update_columns(status: 1)
          redirect_to  acceptboard_login_index_path
    end
    def decline 

        @categories = Category.all
          @place = Place.find(params[:place]) 
          puts "-------------------------------"
          puts params[:place]
          puts "-------------------------------"
          @place.update_columns(status: 2)
          redirect_to deniedboard_login_index_path   
    end
    def new
          @categories = Category.all
          @admin=Admin.new
    end
    def show
         @categories = Category.all
         @category = Category.new(category_params)
    end

    def create
        @admin = Admin.new(admin_params)
        if @admin.save
            session[:admin_id] = @admin.id
            redirect_to dashboard_login_index_path
        else
            render 'new'
        end
    end
    
    private
    def admin_params
    params.require(:admin).permit(:surName, :name, :PD, :email, :phone, :password,:password_confirmation)
	end

   private
    def category_params
    params.require(:category).permit(:name)
  end

end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/login/accept.html.erb
<div class="square">
  <%= stylesheet_link_tag 'index'%>

<div class="square">
<div class = "container">
  <h5>Зөвшөөрсөн газрууд</h5>
  <div class = "card-box container"> 
    <div class="card-deck ">
      <% @accept.each.with_index do |place,index| %>
        <div class="card" style="width: 18rem; max-width: 250px; min-width: 200px; margin-bottom: 20px; border-radius: 20px;">
          <div class = "photo">
            <%= image_tag place.image.to_s %>
            <div class="glow-wrap link ">
              <i class="glow"></i>
            </div>
          </div>

          <div class="card-body">
            <div class="titles">
              
            <%= link_to place.title, place_path(place) %><br> 
            </div>
            <div class="col-lg-12">
              <div class="star">
                <div class="<%=index%>">
          <span class="fa fa-star-o" data-rating="1"></span>
          <span class="fa fa-star-o" data-rating="2"></span>
          <span class="fa fa-star-o" data-rating="3"></span>
          <span class="fa fa-star-o" data-rating="4"></span>
          <span class="fa fa-star-o" data-rating="5"></span>
          <input type="hidden" name="whatever1" class="rating-value" value="<%=place.comments.average(:rating)%>">
        </div>        
              </div>
        
      </div>
             <div class = "description">
                  <%= place.description%>
             </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
            <div class="btn btn-outline-primary btn-lg btn-block">
                  <%= link_to " Татгалзах",controller: 'login', action: 'decline', place: place.id %>    
                </div> 
              </li>
            </ul>
          </div>
        </div> 
      <% end %>
    </div>
  </div>
</div>

<%= will_paginate @accept %>
</div>
</div>

   <script>

    for (var i = 0; i < 4; i++) {
         
  
     var d = "'."+i+" .fa'";
     var $val = "'."+i+" .fa'";
     console.log($val);
     var $star_rating = $('.'+i+' .fa'); 
     console.log($star_rating);
   
     var SetRatingStar = function() {
  return $star_rating.each(function() {
    if (parseInt($star_rating.siblings('input.rating-value').val()) >= parseInt($(this).data('rating'))) {
      return $(this).removeClass('fa-star-o').addClass('fa-star');
    } else {
      return $(this).removeClass('fa-star').addClass('fa-star-o');
    }
  });
};
SetRatingStar();
$(document).ready(function() {

});
    }
    
</script>

app/views/login/dashboard.html.erb
<div class="square">
  <%= stylesheet_link_tag 'index'%>

<div class="square">
<div class = "container">
  <h5>Хүлээгдэж буй газрууд</h5>
  <div class = "card-box container"> 
    <div class="card-deck ">
      <% @pending.each.with_index do |place,index| %>
        <div class="card" style="width: 18rem; max-width: 250px; min-width: 200px; margin-bottom: 20px; border-radius: 20px;">
          <div class = "photo">
            <%= image_tag place.image.to_s %>
            <div class="glow-wrap link ">
              <i class="glow"></i>
            </div>
          </div>

          <div class="card-body">
            <div class="titles">
            <%= link_to place.title, place_path(place) %><br> 
              
            </div>
            <div class="col-lg-12">
              <div class="star">
                <div class="<%=index%>">
          <span class="fa fa-star-o" data-rating="1"></span>
          <span class="fa fa-star-o" data-rating="2"></span>
          <span class="fa fa-star-o" data-rating="3"></span>
          <span class="fa fa-star-o" data-rating="4"></span>
          <span class="fa fa-star-o" data-rating="5"></span>
          <input type="hidden" name="whatever1" class="rating-value" value="<%=place.comments.average(:rating)%>">
        </div>        
              </div>
        
      </div>
             <div class = "description">
                  <%= place.description%>
             </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
            <div class="btn btn-outline-primary btn-sm">
                  <%= link_to " Зөвшөөрөх",controller: 'login', action: 'approve', place: place.id %>    
                </div> 
                 <div class="btn btn-outline-primary btn-sm ">
                  <%= link_to " Татгалзах",controller: 'login', action: 'decline', place: place.id %>    
                </div> 
              </li>
            </ul>
          </div>
        </div> 
      <% end %>
    </div>
  </div>
</div>

<%= will_paginate @pending %>
</div>
</div>

   <script>

    for (var i = 0; i < 4; i++) {
         
  
     var d = "'."+i+" .fa'";
     var $val = "'."+i+" .fa'";
     console.log($val);
     var $star_rating = $('.'+i+' .fa'); 
     console.log($star_rating);
   
     var SetRatingStar = function() {
  return $star_rating.each(function() {
    if (parseInt($star_rating.siblings('input.rating-value').val()) >= parseInt($(this).data('rating'))) {
      return $(this).removeClass('fa-star-o').addClass('fa-star');
    } else {
      return $(this).removeClass('fa-star').addClass('fa-star-o');
    }
  });
};
SetRatingStar();
$(document).ready(function() {

});
    }
    
</script>

app/views/login/denied.html.erb
<div class="square">
	<%= stylesheet_link_tag 'index'%>

<div class="square">
<div class = "container">
  <h5>Татгалзсан газрууд</h5>
  <div class = "card-box container"> 
    <div class="card-deck ">
      <% @denied.each.with_index do |place,index| %>
        <div class="card" style="width: 18rem; max-width: 250px; min-width: 200px; margin-bottom: 20px; border-radius: 20px;">
          <div class = "photo">
            <%= image_tag place.image.to_s %>
            <div class="glow-wrap link ">
              <i class="glow"></i>
            </div>
          </div>

          <div class="card-body">
            <div class="titles">
            <%= link_to place.title, place_path(place) %><br> 
              
            </div>
            <div class="col-lg-12">
              <div class="star">
                <div class="<%=index%>">
          <span class="fa fa-star-o" data-rating="1"></span>
          <span class="fa fa-star-o" data-rating="2"></span>
          <span class="fa fa-star-o" data-rating="3"></span>
          <span class="fa fa-star-o" data-rating="4"></span>
          <span class="fa fa-star-o" data-rating="5"></span>
          <input type="hidden" name="whatever1" class="rating-value" value="<%=place.comments.average(:rating)%>">
        </div>        
              </div>
        
      </div>
             <div class = "description">
                  <%= place.description%>
             </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
            <div class="btn btn-outline-primary btn-lg btn-block">
                  <%= link_to " Зөвшөөрөх",controller: 'login', action: 'approve', place: place.id %>    
                </div> 
              </li>
            </ul>
          </div>
        </div> 
      <% end %>
    </div>
  </div>
</div>

<%= will_paginate @denied %>
</div>
</div>

   <script>

    for (var i = 0; i < 4; i++) {
         
  
     var d = "'."+i+" .fa'";
     var $val = "'."+i+" .fa'";
     console.log($val);
     var $star_rating = $('.'+i+' .fa'); 
     console.log($star_rating);
   
     var SetRatingStar = function() {
  return $star_rating.each(function() {
    if (parseInt($star_rating.siblings('input.rating-value').val()) >= parseInt($(this).data('rating'))) {
      return $(this).removeClass('fa-star-o').addClass('fa-star');
    } else {
      return $(this).removeClass('fa-star').addClass('fa-star-o');
    }
  });
};
SetRatingStar();
$(document).ready(function() {

});
    }
    
</script>

app/views/login/index.html.erb
<style>
  body {
    font-family: 'Lato', sans-serif;
    background-image: url(background-rightbox.png);
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    margin: 0;
    padding: 0;
}

.login-box {
    position: absolute;
    margin-top: 150px;
    left: 50%;
    transform: translate(-50%, -50%);
    color: #222;
    box-sizing: border-box;
    background: #fff;
    padding: 40px;
    width: 400px;
    height: 420px;
    
}

h3 {
    float: left;
    font-size: 20px;
    border-bottom: 4px solid;
    margin-bottom: 30px;
    padding: 13px 0;
    text-align: center;
}

.textbox {
    font-size: 16px;
    width: 100%;
    overflow: hidden;
    border-bottom: 1px solid;
    padding: 8px 0;
    margin: 8px 0;
}

.textbox i {
    width: 10%;
    padding: 5px;
    float: left;
    text-align: center;
}

.textbox input {
    border: none;
    background: none;
    color: #222;
    font-size: 16px;
    width: 90%;
    margin: auto;
}

input[type="submit"] {
    width: 100%;
    border: 2px solid #222;
    font-size: 20px;
    background: none;
    cursor: pointer;
    cursor: pointer;
    font-family: 'lato', sans-serif;
    padding: 5px;
    margin: 10px 0;
}

.login-box:after {
    content: "";
    display: table;
    clear: both;
}

</style>
<div class = "square" >
<div id="login-box" class="login-box">
        <h3>Нэвтрэх</h3>
         
          <%= form_for(@admin, url:login_login_index_path) do |f| %>
            <% flash.each do |key, value| %>
                <div>
                      <%= value %>
                </div>
          	<% end %>

            <div class="textbox">
          <i class="fa fa-user"></i>
            <%= f.email_field :email, class: 'form-control', placeholder: "И-мэйл хаяг" %>
        </div>
        <div class="textbox">
            <i class="fas fa-lock"></i>
            <%= f.password_field :password, class: 'form-control', placeholder: "Нууц үг" %>
        </div>
            <%= f.submit "Нэвтрэх", class: "btn btn-primary" %>
        <% end %>
        
        </div>
    </div>   
    </div>

app/views/login/new.html.erb
<style>
  body {
    font-family: 'Lato', sans-serif;
    background-image: url(background-rightbox.png);
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    margin: 0;
    padding: 0;
}

.login-box {
    position: absolute;
    margin-top: 150px;
    left: 50%;
    transform: translate(-50%, -50%);
    color: #222;
    box-sizing: border-box;
    background: #fff;
    padding: 40px;
    width: 400px;
    height: 420px;
}

h3{
    float: left;
    font-size: 20px;
    border-bottom: 4px solid;
    margin-bottom: 30px;
    padding: 13px 0;
}

.textbox {
    font-size: 16px;
    width: 100%;
    overflow: hidden;
    border-bottom: 1px solid;
    padding: 0;
    margin: 8px 0;
}

.textbox i {
    width: 10%;
    padding: 5px;
    float: left;
    text-align: center;
}

.textbox input {
    border: none;
    background: none;
    color: #222;
    font-size: 16px;
    width: 90%;
    margin: auto;
}

input[type="submit"] {
    width: 100%;
    border: 2px solid #222;
    font-size: 20px;
    background: none;
    cursor: pointer;
    cursor: pointer;
    font-family: 'lato', sans-serif;
    padding: 5px;
    margin: 10px 0;
}

.login-box:after {
    content: "";
    display: table;
    clear: both;
}
.fa{
    padding: 15px !important
}
</style>
<div class="square">
<div id="login-box" class="login-box">
    <h3>Бүртгүүлэх</h3>
    <%= form_for(@admin, url: login_index_path) do |f| %>
        <% @admin.errors.full_messages.each do |msg| %>
            <li class="error"><%= msg %></li>
          <% end %>
      <div class="textbox">
          <i class="fa fa-user"></i>
        <%= f.text_field :surName, class: 'form-control', placeholder: "Овог" %>
    </div>
    <div class="textbox">
          <i class="fa fa-user"></i>
        <%= f.text_field :name, class: 'form-control', placeholder: "Хэрэглэгчийн нэр" %>
    </div>
    <div class="textbox">
          <i class="fa fa-user"></i>
        <%= f.text_field :PD, class: 'form-control', placeholder: "РД" %>
    </div>
        <div class="textbox">
          <i class="fa fa-user"></i>
        <%= f.email_field :email, class: 'form-control', placeholder: "И-мэйл хаяг" %>
        </div>
        <div class="textbox">
          <i class="fa fa-user"></i>
        <%= f.text_field :phone, class: 'form-control', placeholder: "Утас" %>
    </div>
        <div class="textbox">
            <i class="fas fa-lock"></i>
        <%= f.password_field :password, class: 'form-control', placeholder: "Нууц үг" %>
        </div>
        <%= f.submit "Бүртгүүлэх", class: "btn btn-primary" %>
    <% end %>
    </div>
</div>
</div>

app/views/login/show.html.erb
<div class="square">
	 <%= form_with scope: :category, url: login_index_path, local: true do |form| %>
     	<div class="row form-group">
			    <div class="col-md-3">
			      <label><p>Төрөл</p></label>
			    </div>
			    <div class="col-md-9">
			      <%= form.text_field :name %>
			    </div>
  	    </div>	
  	     <%= form.submit 'Нэмэх', class: "btn btn-outline-primary" %>
      <% end -%>
</div>