config/routes.rb
Rails.application.routes.draw do
  
  get 'places/check'
  get 'places/category'
   resources :places do 
   	resources :comments
   	resources :categories
   end

  root 'places#index'
  root 'places#new'
  root 'places#check'
  root 'places#submit'
 
  root to: 'session#index'
  root to: 'login#index'

resources :places do
    collection do
   get 'category', to: "places#category"


    end
  end

resources :login do
    collection do
      get 'signup', to: "login#new"
      get 'login', to: "login#index"
      post 'login', to: "login#login"
      get 'dashboard', to: "login#dashboard"
      get 'approve',to: "login#approve"
      get 'decline',to: "login#decline"
      get 'deniedboard',to: "login#denied"
      get 'acceptboard',to: "login#accept"
      post 'create',to: "login#show"


    end
  end

   resources :session do
    collection do
      get 'signup', to: "session#new"
      get 'login', to: "session#index"
      post 'login', to: "session#login"
      get 'logout', to: "session#logout"
      get 'dashboard', to: "session#dashboard"
    end
  end

 end

app/models/place.rb
class Place < ApplicationRecord
	has_many :comments, dependent: :destroy
	has_and_belongs_to_many :categories 
	mount_uploader :image,ImageUploader
	belongs_to :user

	
	def self.search(search)
		if search
			 where(["title LIKE ?", "%#{search}%"])
		else
			order("updated_at DESC").where(status: 1)
		end
	end

	def self.search1(search1)
		if search1
			 where(["title LIKE ?", "%#{search}%"])
		else
			order("updated_at DESC").where(status: 1)
		end
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
     @places =  Place.where(status:1).limit(4).order("count DESC")
     @categories = Category.all
  end

  def show
   @categories = Category.all
   
    @place = Place.find(params[:id])
    @average = @place.comments.average(:rating)
    @count = @place.count
    @place.update_columns(count: @count+1)
    puts @count   
  end
  def edit
  @Place = Place.find(params[:id])
  end
  def submit
    @status = @place.status
    @place.update_columns(status: @status = 1)
  end

  def edit
    @Place = Place.find(params[:id])
  end

  def submit
    @status = @place.status
    @place.update_columns(status: @status = 1)
  end
	def new
    @places = Place.new
    @categories = Category.all
  end

  def check
    @categories = Category.all
    @check = Place.search(params[:search]).where(status:1).paginate(:page => params[:page], per_page:4)
  end
  
  def create
    @user = User.find(session[:user_id])
    @place = @user.places.create(place_params)
    @category = Category.find(params[:category])
    @place.categories << @category
    @place.save
    redirect_to @place
  end
  def category
    @categories = Category.all
    @category = Category.find(params[:category])
    puts @category
    @places = @category.places.search1(params[:search1]).where(status:1).paginate(:page => params[:page], per_page:4)
  end
 
 
  private
  def place_params
    params.require(:place).permit(:title, :image, :description, :timetable, :opentime, :closetime, :price, :location, :longitude, :latitude, :phone, :category)
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_footer.html.erb
 <%= stylesheet_link_tag    'footer'%>
 <footer >
  <section id="footer">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
          <ul class="list-unstyled list-inline social text-center">
            <li class="list-inline-item"><a href="https://www.facebook.com/anujin.baatartsogt.56"><i class="fa fa-facebook">
            </i></a></li>
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="https://plus.google.com/u/0/103281051439483057699"><i class="fa fa-google-plus"></i></a></li>
            <li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope"></i></a></li>
          </ul>
        </div>
      </hr>
    </div>  
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
        <p>Unimedia Solutions LLC</p>
        <p class="h6">&copy All right Reversed.</p>
      </div>
    </hr>
  </div>  
</div>
</section>
</footer>

app/views/places/_navbar.html.erb
 <link href="https://fonts.googleapis.com/css?family=Lora:400,400i&amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet"> 
 <%= stylesheet_link_tag 'navbar'%>

  <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
     <%= link_to image_tag("tlogo1.png", alt: "logo"), '/', class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">

       <p class= "nav-link"> <%= link_to 'Эхлэл', controller: 'places', action: 'index' %></p>
      
      </li>
      <li class="nav-item">
       <p class= "nav-link"><%= link_to 'Жагсаалт', controller: 'places', action: 'check' %></p>
      </li>
      <li class="nav-item">
       <p class="nav-link"> <%= link_to 'Газар нэмэх', controller: 'places', action: 'new' %></p>
      </li>
         <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Төрөл
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <% @categories.each do |category| %>
         <a class="dropdown-item"><%= link_to category.name, controller: 'places', action: 'category', category: category.id %>
         </a>
         <% end %>
       </div>
     </li>
        <li>
      <div class="nav-item ml-auto">
        <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#demo" style="color:white;"><i class="fa fa-search" style="font-size:20px"></i></button>  
      </div>
      <div class = "nav-item ml-auto">          
      </div>
    </li>
    <li>
    <div class="nav-item dropdown ml-auto" >
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= session[:user_name] %>
      <i class="fa fa-user" style="font-size:20px"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      <a class="dropdown-item-text">
        <%= link_to 'Нэвтрэх', controller: 'session', action: 'login' %>            
      </a>
      <a class="dropdown-item">
        <%= link_to 'Бүртгүүлэх', controller: 'session', action: 'new' %>
      </a>
      <a class="dropdown-item">
        <%= link_to 'Минийн нэмсэн газрууд', controller: 'session', action: 'dashboard' %>
      </a>
      <div class="dropdown-divider">
      </div> 
      <a class="dropdown-item-text">
        <%= link_to 'Гарах', controller: 'session', action: 'logout' %>
      </a>
    </div>
  </div> 
    </li>
    </ul>
  </div>
</nav>



app/views/places/category.html.erb
<br>
<br>
<%= stylesheet_link_tag 'index'%>
<div class="square">
  <div class = "container">
    <H3><%= @category.name %></H3>
    <div class = "card-box container"> 
      <div class="card-deck ">
        <% @places.each.with_index do |place,index| %>
        <div class="card" style="width: 18rem; max-width: 250px; min-width: 200px; margin-bottom: 20px; border-radius: 20px;">
          <div class = "photo">
           <%= image_tag place.image.to_s %>
           <div class="glow-wrap link ">
             <i class="glow"></i>
           </div>
         </div>
         <div class="card-body">
           <div class="titles">
            <%= link_to place.title, place_path(place) %><br> 
          </div>
          <div class="col-lg-12">
            <div class="star">
             <div class="<%=index%>">
              <span class="fa fa-star-o" data-rating="1"></span>
              <span class="fa fa-star-o" data-rating="2"></span>
              <span class="fa fa-star-o" data-rating="3"></span>
              <span class="fa fa-star-o" data-rating="4"></span>
              <span class="fa fa-star-o" data-rating="5"></span>
              <input type="hidden" name="whatever1" class="rating-value" value="<%=place.comments.average(:rating)%>">
            </div>        
          </div>
        </div>
        <div class = "description">
          <%= place.description%>
        </div>
        <ul class="list-group list-group-flush">
         <li class="list-group-item">
          <a href="places/1"><span class="fa fa-facebook iconlogo"></span> </a>
          <a href=""><span class="fa fa-google logo iconlogo"></span></a>
          <a href=""> <span class="fa fa-twitter iconlogo"></span></a>      
        </li>  
      </ul>
    </div>
  </div> 
  <% end %>
</div>
</div>
</div>
<%= will_paginate @places %>
</div>
</div>
<script>
  for (var i = 0; i < 4; i++) {
   var d = "'."+i+" .fa'";
   var $val = "'."+i+" .fa'";
   console.log($val);
   var $star_rating = $('.'+i+' .fa'); 
   console.log($star_rating);
   var SetRatingStar = function() {
    return $star_rating.each(function() {
      if (parseInt($star_rating.siblings('input.rating-value').val()) >= parseInt($(this).data('rating'))) {
        return $(this).removeClass('fa-star-o').addClass('fa-star');
      } else {
        return $(this).removeClass('fa-star').addClass('fa-star-o');
      }
    });
  };
  SetRatingStar();
  $(document).ready(function() {
  });
}
</script>

app/views/places/check.html.erb
<style type="text/css">
.checkbox-inline {
  margin-top: 10px;
  font-size: 18px;
  padding: 16px 13px 13px 15px;
  margin-bottom: 12px;
}
.form-check-inline{
  margin-left: 0px;
  margin-right: 0px;
}
.w3 {
  margin-top: 10px;
  margin-right: 0px;
  margin-bottom: 12px;
  font-size: 18px;
}
.agileits {
  text-indent-size: 20px; 
  margin-bottom: 12px;
}
input[type=text], textarea {
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 70%;
  font-size: 14px;
  padding: 10px 40px 10px 68px;
  margin-bottom: 5px;
}
.center {
  border: 1px solid #e4e8ec !important;
  margin-top: 5px;
  margin-left: 10px;
}
.zurag{
  background-image: url(images/1.jpeg);
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center;
  width: 100%;
  height: 20%;
}
.new{
  padding: 10px;
}
.background{
  max-width: 700px;
  background: rgba(120, 109, 118, 0.36 );
  margin: auto;
  margin-bottom: 50px;
}
.background p{
  font-size: 17px !important;
  color: white;
}
.form-group{
  padding: 30px;
  margin-bottom: -50px;
}
.time{
}
.time select{
  width: 30%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  resize: vertical;
}
.pagination{
  justify-content: center;
}
#demo{  
}
</style>
<%= stylesheet_link_tag 'index'%>
<br>
<br>
<%= stylesheet_link_tag 'index'%>
<div class="square">
  <div class = "container">
    <div id="demo" class="collapse show">
     <div class = "search">
      <%= form_tag places_check_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Хайх" ,class: "btn btn-outline-primary  "  %>
      <% end %>
    </div>  
  </div>  
  <h5>Хамгийн сүүлд нэмэгдсэн</h5>
  <div class = "card-box container"> 
    <div class="card-deck ">
      <% @check.each.with_index do |place,index| %>
      <div class="card" style="width: 18rem; max-width: 250px; min-width: 200px; margin-bottom: 20px; border-radius: 20px;">
        <div class = "photo">
          <%= image_tag place.image.to_s %>
          <div class="glow-wrap link ">
            <i class="glow"></i>
          </div>
        </div>
        <div class="card-body">
          <div class="titles">
            <%= link_to place.title, place_path(place) %><br> 
          </div>
          <div class="col-lg-12">
            <div class="star">
              <div class="<%=index%>">
                <span class="fa fa-star-o" data-rating="1"></span>
                <span class="fa fa-star-o" data-rating="2"></span>
                <span class="fa fa-star-o" data-rating="3"></span>
                <span class="fa fa-star-o" data-rating="4"></span>
                <span class="fa fa-star-o" data-rating="5"></span>
                <input type="hidden" name="whatever1" class="rating-value" value="<%=place.comments.average(:rating)%>">
              </div>        
            </div>
          </div>
          <div class = "description">
            <%= place.description%>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <a href="places/1"><span class="fa fa-facebook iconlogo"></span> </a>
              <a href=""><span class="fa fa-google logo iconlogo"></span></a>
              <a href=""> <span class="fa fa-twitter iconlogo"></span></a>      
            </li>  
          </ul>
        </div>
      </div> 
      <% end %>
    </div>
  </div>
</div>
<%= will_paginate @check %>
</div>
</div>
<script>
  for (var i = 0; i < 4; i++) {
   var d = "'."+i+" .fa'";
   var $val = "'."+i+" .fa'";
   console.log($val);
   var $star_rating = $('.'+i+' .fa'); 
   console.log($star_rating);
   var SetRatingStar = function() {
    return $star_rating.each(function() {
      if (parseInt($star_rating.siblings('input.rating-value').val()) >= parseInt($(this).data('rating'))) {
        return $(this).removeClass('fa-star-o').addClass('fa-star');
      } else {
        return $(this).removeClass('fa-star').addClass('fa-star-o');
      }
    });
  };
  SetRatingStar();
  $(document).ready(function() {
  });
}
</script>

app/views/places/edit.html.erb
<h1>Edit Place</h1>
 
<%= form_with(model: @place, local: true) do |form| %>
  <div class="row form-group">
            <div class="col-md-3">
            <label><p>Төрөл</p></label>
          </div>
                      
                 
                  
          </div>
        <div class="row form-group">
          <div class="col-md-3">
            <label><p>Гарчиг</p></label>
          </div>
          <div class="col-md-9">
            <%= form.text_field :title %>
          </div>
          </div>
          <div class="row form-group">
         <div class="col-md-3">
            <label><p>Зургийн файл</p></label>
          </div>
          <div class="col-md-9">
            <%= form.file_field  :image%> 
          </div>
          </div>
          <div class="row form-group">
          <div class="col-md-3">
            <label><p>Тайлбар</p></label>
          </div>
          <div class="col-md-9">
            <%= form.text_area :description %>
          </div>
          </div>
          <div class="row form-group">
          <div class="col-md-3">
            <label><p>Цагийн хуваарь</p></label>
          </div>
          <div class="col-md-9">
           <%= form.text_field :timetable %>
          </div>
          </div>
          <div class="row form-group">
          <div class="col-md-3">
            <label><p>Нээх цаг</p></label>
          </div>
          <div class="col-md-9">
            <div class="time">
              <%= form.time_select :opentime %>   
            </div>
          </div>
          </div>
          <div class="row form-group">
          <div class="col-md-3">
            <label><p>Хаах цаг</p></label>
          </div>
          <div class="col-md-9">
            <div class="time">
              <%= form.time_select :closetime %>    
            </div>
          </div>
          </div>
          <div class="row form-group">
          <div class="col-md-3">
            <label><p>Үнэ</p></label>
          </div>
          <div class="col-md-9">
            <div class="time">
              <%= form.text_field :price %>
            </div>
          </div>
          </div>
          <div class="row form-group">
          <div class="col-md-3">
            <label><p>Хаяг</p></label>
          </div>
          <div class="col-md-9">
            <div class="time">
              <%= form.text_field :location%>
            </div>
          </div>
          </div>
          <div class="row form-group">
          <div class="col-md-3">
            <label><p>Уртраг</p></label>
          </div>
          <div class="col-md-9">
            <div class="time">
              <%= form.text_field :longitude%>
            </div>
          </div>
          </div>
          <div class="row form-group">
          <div class="col-md-3">
            <label><p>Өргөрөг</p></label>
          </div>
          <div class="col-md-9">
            <div class="time">
              <%= form.text_field :latitude%>
            </div>
          </div>
          </div>
          <div class="row form-group">
          <div class="col-md-3">
            <label><p>Утас</p></label>
          </div>
          <div class="col-md-9">
            <div class="time">
              <%= form.text_field :phone%>
            </div>
          </div>
          </div>
          <div class="row form-group">
            <div class="col-md-12">
            <%= form.submit %>
          </div>
          </div>  
<% end %>
 
<%= link_to 'Back', places_path %>

app/views/places/header.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src=".../800x400?auto=yes&bg=777&fg=555&text=First slide" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src=".../800x400?auto=yes&bg=666&fg=444&text=Second slide" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src=".../800x400?auto=yes&bg=555&fg=333&text=Third slide" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/places/index.html.erb
<%= stylesheet_link_tag 'index'%>
<div class="square">
  <div class = "container">
    <h5>Хамгийн их хандалттай</h5>
    <div class = "card-box container"> 
      <div class="card-deck ">
       <% @places.each.with_index do |place,index| %>
        <div class="card" style="width: 18rem; max-width: 250px; min-width: 200px; margin-bottom: 20px; border-radius: 20px;">
          <div class = "photo">
            <%= image_tag place.image.to_s %>
            <div class="glow-wrap link ">
              <i class="glow"></i>
            </div>
          </div>
          <div class="card-body">
            <div class="titles">
             <%= link_to place.title, place_path(place) %><br> 
            </div>
            <div class="col-lg-12">
              <div class="star">
                <div class="<%=index%>">
                  <span class="fa fa-star-o" data-rating="1"></span>
                  <span class="fa fa-star-o" data-rating="2"></span>
                  <span class="fa fa-star-o" data-rating="3"></span>
                  <span class="fa fa-star-o" data-rating="4"></span>
                  <span class="fa fa-star-o" data-rating="5"></span>
                   <p class="fa fa-eye" style="margin-left: 5px"  ><span class="badge badge-dark" style="margin-left: 5px"><%=place.count %></span></p>
                  <input type="hidden" name="whatever1" class="rating-value" value="<%=place.comments.average(:rating)%>">
                </div>       

              </div>

            </div>
           
            <div class = "description">
              <%= place.description%>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <a href="places/1"><span class="fa fa-facebook iconlogo"></span> </a>
                <a href=""><span class="fa fa-google logo iconlogo"></span></a>
                <a href=""> <span class="fa fa-twitter iconlogo"></span></a>      
              </li>  
            </ul>
          </div>
        </div> 
       <% end %>
      </div>
    </div>
  </div>
</div>
<script>
for (var i = 0; i < 4; i++) {
     var d = "'."+i+" .fa'";
     var $val = "'."+i+" .fa'";
     console.log($val);
     var $star_rating = $('.'+i+' .fa'); 
     console.log($star_rating);
     var SetRatingStar = function() {
       return $star_rating.each(function() {
      if (parseInt($star_rating.siblings('input.rating-value').val()) >= parseInt($(this).data('rating'))) {
      return $(this).removeClass('fa-star-o').addClass('fa-star');
      } 
      else {
      return $(this).removeClass('fa-star').addClass('fa-star-o');
      }
     });
    };
SetRatingStar();
$(document).ready(function() {
});
}
</script>

app/views/places/info.html.erb
 <%= render 'header' %>

app/views/places/new.html.erb
<div class = "square">
	<div class="zurag">
		<div class="container" style="margin-top: 72px;">
			<br>
			<center><h1 style="margin-top: 20px; color: white;">Газар нэмэх</h1></center>
			<div class="background">
				<%= form_with scope: :place, url: places_path,:html => {:name => 'form'}, local: true do |form| %>
				<div class="row form-group">
					<div class="col-md-3">
						<label><p>Төрөл</p></label>
					</div>
					<div class="col-md-9">
						<select name="category">
							<option value="none" selected="" disabled="">Төрөл сонгох</option>
							<% @categories.each do |category| %>
							<option value=<%= category.id %> > <%= category.name %></option>
							<% end %>
						</select>
					</div>		                
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						<label><p>Гарчиг</p></label>
					</div>
					<div class="col-md-9">
						<%= form.text_field :title, :required => true,:onkeyup => "return validateForm();"  %>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						<label><p>Зургийн файл</p></label>
					</div>
					<div class="col-md-9">
						<%= form.file_field :image %> 
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						<label><p>Тайлбар</p></label>
					</div>
					<div class="col-md-9">
						<%= form.text_area :description, :required => true,:onkeyup => "return validateForm();"  %>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						<label><p>Цагийн хуваарь</p></label>
					</div>
					<div class="col-md-9">
						<%= form.text_field :timetable, :required => true,:onkeyup => "return validateForm();"  %>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						<label><p>Нээх цаг</p></label>
					</div>
					<div class="col-md-9">
						<div class="time">
							<%= form.time_select :opentime, :required => true,:onkeyup => "return validateForm();"  %>		
						</div>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						<label><p>Хаах цаг</p></label>
					</div>
					<div class="col-md-9">
						<div class="time">
							<%= form.time_select :closetime, :required => true,:onkeyup => "return validateForm();"  %>		
						</div>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						<label><p>Үнэ</p></label>
					</div>
					<div class="col-md-9">
						<div class="time">
							<%= form.text_field :price, :required => true,:onkeyup => "return validateForm();"  %>
						</div>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						<label><p>Хаяг</p></label>
					</div>
					<div class="col-md-9">
						<div class="time">
							<%= form.text_field :location, :required => true,:onkeyup => "return validateForm();" %>
						</div>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						<label><p>Уртраг</p></label>
					</div>
					<div class="col-md-9">
						<div class="time">
							<%= form.text_field :longitude, :required => true,:onkeyup => "return validateForm();" %>
						</div>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						<label><p>Өргөрөг</p></label>
					</div>
					<div class="col-md-9">
						<div class="time">
							<%= form.text_field :latitude, :required => true,:onkeyup => "return validateForm();" %>
						</div>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-3">
						<label><p>Утас</p></label>
					</div>
					<div class="col-md-9">
						<div class="time">
							<%= form.text_field :phone, :required => true,:onkeyup => "return validateForm();" %>
						</div>
					</div>
				</div>
				<div class="row form-group">
					<div class="col-md-12">
						<%= form.submit 'Нэмэх', class: "btn btn-outline-primary" %>
					</div>
				</div>
				<% end %>
			</div>
		</div>
	</div>	
</div>
<script>

function validateForm() {
  
  var  title = document.forms["form"]["article[title]"].value;
  var  description = document.forms["form"]["place[description]"].value;
  var  price = document.forms["form"]["place[price]"].value;
  var  location = document.forms["form"]["place[location]"].value;
  var  longitude = document.forms["form"]["place[longitude]"].value;
  var  latitude = document.forms["form"]["place[latitude]"].value;
  var  phone = document.forms["form"]["place[phone]"].value;

  var msg="";
  var check  = /^[a-zA-Z0-9_.-]*$/;
   if (!check.test(title)) {
        msg="Гарчигийн утгыг шалгана уу !";
       document.getElementById("errorTitle").innerHTML =msg;
    }
    else{
      msg="";
      document.getElementById("errorTitle").innerHTML =msg;
    }

   if (!check.test(x)){
    msg="please check value of text";
    document.getElementById("errorText").innerHTML =msg;
  } else{
   msg=="";
   document.getElementById("errorText").innerHTML =msg;
    
  }
 
 
  if(msg =! ""){

    return false;
  }
  else{
    
     
    return true;
  }
} 
</script>